### ISSUE TITLE
Error when paying another user

### ISSUE THREAD

**Issue by Joshua-Burt** [Joshua-Burt/BlockObama#8]
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\{USER}\PycharmProjects\BlockObama 2.0\main.py", line 160, in pay
    await ctx.send("**{}** paid **{}** - **{:,}** points".format(
ValueError: Cannot specify ',' with 's'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\{USER}\PycharmProjects\BlockObama 2.0\main.py", line 190, in on_command_error
    raise error
  File "C:\Python310\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Python310\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Python310\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: Cannot specify ',' with 's'.

**Comment by Joshua-Burt** [comment]
Old bug
